/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;
        
import ComponentesElectronicos.*;
import Excepctions.*;
import Persistencia.*;
import Personas.*;

import javax.swing.*;
import java.awt.*;
import java.io.FileNotFoundException;
import java.util.ArrayList;
/**
 *
 * @author rodri
 */
public class ElectroLabFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ElectroLabFrame.class.getName());
    
    private Inventario inventario;
    private ArrayList<Usuario> usuarios;
    private ArrayList<Prestamo> prestamos;
    private JTextArea areaTexto;
    
    private JTabbedPane pestanas;
    private JPanel panelInventario;
    private JPanel panelUsuarios;
    private JPanel panelPrestamos;
    /**
     * Creates new form MenuGrafico
     */
    public ElectroLabFrame() throws ClassNotFoundException, FileNotFoundException {
        initComponents();
        inventario = PersistenciaInventario.cargar();
        usuarios = PersistenciaUsuarios.cargar();
        prestamos = PersistenciaPrestamos.cargar();

        setLocationRelativeTo(null);

        jTextFieldCarrera.setText("");
        jTextFieldSemestre.setText("");

        jTextFieldNombreUsuario.setText("");
        jTextFieldIDUsuario.setText("");

        jTextFieldNomInventario.setText("");
        jTextFieldCodInventario.setText("");
        jTextFieldStockInventario.setText("");
        jTextFieldValorInventario.setText("");

        jTextFieldIDUsuPrestamo.setText("");
        jTextFieldCodCompPrestamo.setText("");
        jTextFieldCantPrestamo.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profesion = new javax.swing.ButtonGroup();
        Componentes = new javax.swing.ButtonGroup();
        jTitulo = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonEstudiante = new javax.swing.JRadioButton();
        jRadioDocente = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonSalir1 = new javax.swing.JButton();
        jTextFieldCarrera = new javax.swing.JTextField();
        jTextFieldSemestre = new javax.swing.JTextField();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jTextFieldIDUsuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldCantPrestamo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldIDUsuPrestamo = new javax.swing.JTextField();
        jTextFieldCodCompPrestamo = new javax.swing.JTextField();
        jButtonRealizarPrestamo = new javax.swing.JButton();
        jButtonDevolverPrestamo = new javax.swing.JButton();
        jButtonMostrarPrestamos = new javax.swing.JButton();
        jButtonSalir3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPrestamos = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNomInventario = new javax.swing.JTextField();
        jTextFieldCodInventario = new javax.swing.JTextField();
        jTextFieldStockInventario = new javax.swing.JTextField();
        jTextFieldValorInventario = new javax.swing.JTextField();
        jRadioButtonResistencia = new javax.swing.JRadioButton();
        jRadioButtonCapacitor = new javax.swing.JRadioButton();
        jRadioButtonSensor = new javax.swing.JRadioButton();
        jButtonAgregarComponente = new javax.swing.JButton();
        jButtonBuscarComponente = new javax.swing.JButton();
        jButtonMostrarInventario = new javax.swing.JButton();
        jButtonSalir2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInventario = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));

        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("ELECTROLAB MANAGER");
        jTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("ID:");

        Profesion.add(jRadioButtonEstudiante);
        jRadioButtonEstudiante.setSelected(true);
        jRadioButtonEstudiante.setText("Estudiante");
        jRadioButtonEstudiante.addActionListener(this::jRadioButtonEstudianteActionPerformed);

        Profesion.add(jRadioDocente);
        jRadioDocente.setText("Docente");
        jRadioDocente.addActionListener(this::jRadioDocenteActionPerformed);

        jLabel3.setText("Carrera:");

        jLabel4.setText("Semestre:");

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(this::jButtonRegistrarActionPerformed);

        jButtonSalir1.setText("Salir");
        jButtonSalir1.addActionListener(this::jButtonSalir1ActionPerformed);

        jTextFieldCarrera.setText("jTextField1");

        jTextFieldSemestre.setText("jTextField2");

        jTextFieldNombreUsuario.setText("jTextField1");

        jTextFieldIDUsuario.setText("jTextField2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonSalir1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldCarrera))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioDocente)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButtonRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jPanelMenu.addTab("Usuarios", jPanel1);

        jTextFieldCantPrestamo.setText("jTextField3");

        jLabel9.setText("ID Usuario:");

        jLabel10.setText("Codigo Componente:");

        jLabel11.setText("Cantidad:");

        jTextFieldIDUsuPrestamo.setText("jTextField3");

        jTextFieldCodCompPrestamo.setText("jTextField3");

        jButtonRealizarPrestamo.setText("Realizar Prestamo");

        jButtonDevolverPrestamo.setText("Devolver Prestamo");

        jButtonMostrarPrestamos.setText("Mostrar  Prestamos");

        jButtonSalir3.setText("Salir");
        jButtonSalir3.addActionListener(this::jButtonSalir3ActionPerformed);

        jTextAreaPrestamos.setColumns(20);
        jTextAreaPrestamos.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPrestamos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIDUsuPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodCompPrestamo)
                            .addComponent(jTextFieldCantPrestamo)))
                    .addComponent(jButtonRealizarPrestamo)
                    .addComponent(jButtonDevolverPrestamo)
                    .addComponent(jButtonMostrarPrestamos)
                    .addComponent(jButtonSalir3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldIDUsuPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldCodCompPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldCantPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addComponent(jButtonRealizarPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButtonDevolverPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarPrestamos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalir3)
                        .addGap(48, 48, 48))))
        );

        jPanelMenu.addTab("Prestamos", jPanel3);

        jLabel5.setText("Nombre:");

        jLabel6.setText("Codigo:");

        jLabel7.setText("Stock:");

        jLabel8.setText("Valor:");

        jTextFieldNomInventario.setText("jTextField3");

        jTextFieldCodInventario.setText("jTextField3");

        jTextFieldStockInventario.setText("jTextField3");

        jTextFieldValorInventario.setText("jTextField3");

        Componentes.add(jRadioButtonResistencia);
        jRadioButtonResistencia.setSelected(true);
        jRadioButtonResistencia.setText("Resistenica");

        Componentes.add(jRadioButtonCapacitor);
        jRadioButtonCapacitor.setText("Capacitor");

        Componentes.add(jRadioButtonSensor);
        jRadioButtonSensor.setText("Sensor");

        jButtonAgregarComponente.setText("Agregar");

        jButtonBuscarComponente.setText("Buscar");

        jButtonMostrarInventario.setText("Mostrar Inventario");

        jButtonSalir2.setText("Salir");
        jButtonSalir2.addActionListener(this::jButtonSalir2ActionPerformed);

        jTextAreaInventario.setColumns(20);
        jTextAreaInventario.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInventario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodInventario)
                            .addComponent(jTextFieldStockInventario)
                            .addComponent(jTextFieldValorInventario)))
                    .addComponent(jRadioButtonResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarComponente)
                    .addComponent(jButtonBuscarComponente)
                    .addComponent(jButtonMostrarInventario)
                    .addComponent(jButtonSalir2))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNomInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCodInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldStockInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldValorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonResistencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCapacitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSensor)
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregarComponente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscarComponente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanelMenu.addTab("Inventario", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstudianteActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("Carrera: ");
        jLabel4.setVisible(true);
        jLabel4.setText("Semestre: ");
        jTextFieldSemestre.setVisible(true);
    }//GEN-LAST:event_jRadioButtonEstudianteActionPerformed

    private void jRadioDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDocenteActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("Especialidad: ");
        jLabel4.setVisible(false);
        jTextFieldSemestre.setVisible(false);
    }//GEN-LAST:event_jRadioDocenteActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        try {
            String nombre= jTextFieldNombreUsuario.getText();
            String id= jTextFieldIDUsuario.getText();
            if (jRadioButtonEstudiante.isSelected()) {
                String carrera= jTextFieldCarrera.getText();
                int semestre= Integer.parseInt(jTextFieldSemestre.getText());
                Estudiante e= new Estudiante(nombre,id,carrera,semestre);
                usuarios.add(e);
                JOptionPane.showMessageDialog(this,"Estudiante registrado");
            } else {
                String especialidad= jTextFieldCarrera.getText();
                Docente d= new Docente(nombre,id,especialidad);
                usuarios.add(d);
                JOptionPane.showMessageDialog(this,"Docente registrado");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Ingrese valores validos");
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalir1ActionPerformed

    private void jButtonSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalir2ActionPerformed

    private void jButtonSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalir3ActionPerformed
    
    

        
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Componentes;
    private javax.swing.ButtonGroup Profesion;
    private javax.swing.JButton jButtonAgregarComponente;
    private javax.swing.JButton jButtonBuscarComponente;
    private javax.swing.JButton jButtonDevolverPrestamo;
    private javax.swing.JButton jButtonMostrarInventario;
    private javax.swing.JButton jButtonMostrarPrestamos;
    private javax.swing.JButton jButtonRealizarPrestamo;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JButton jButtonSalir2;
    private javax.swing.JButton jButtonSalir3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jPanelMenu;
    private javax.swing.JRadioButton jRadioButtonCapacitor;
    private javax.swing.JRadioButton jRadioButtonEstudiante;
    private javax.swing.JRadioButton jRadioButtonResistencia;
    private javax.swing.JRadioButton jRadioButtonSensor;
    private javax.swing.JRadioButton jRadioDocente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaInventario;
    private javax.swing.JTextArea jTextAreaPrestamos;
    private javax.swing.JTextField jTextFieldCantPrestamo;
    private javax.swing.JTextField jTextFieldCarrera;
    private javax.swing.JTextField jTextFieldCodCompPrestamo;
    private javax.swing.JTextField jTextFieldCodInventario;
    private javax.swing.JTextField jTextFieldIDUsuPrestamo;
    private javax.swing.JTextField jTextFieldIDUsuario;
    private javax.swing.JTextField jTextFieldNomInventario;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    private javax.swing.JTextField jTextFieldSemestre;
    private javax.swing.JTextField jTextFieldStockInventario;
    private javax.swing.JTextField jTextFieldValorInventario;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
