/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import ComponentesElectronicos.*;
import Excepctions.*;
import Persistencia.*;
import Personas.*;

import javax.swing.*;
import java.awt.*;
import java.io.FileNotFoundException;
import java.util.ArrayList;
/**
 *
 * @author rodri
 */
public class ElectroLabFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ElectroLabFrame.class.getName());
    
    private Inventario inventario;
    private ArrayList<Usuario> usuarios;
    private ArrayList<Prestamo> prestamos;
    private JTextArea areaTexto;
    /**
     * Creates new form MenuGrafico
     */
    public ElectroLabFrame() throws ClassNotFoundException, FileNotFoundException {
        initComponents();
        inicializaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ElectroLab Manager");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel2");

        jLabel4.setText("jLabel2");

        jLabel5.setText("jLabel2");

        jLabel6.setText("jLabel2");

        jLabel7.setText("jLabel2");

        jLabel8.setText("jLabel2");

        jLabel9.setText("jLabel2");

        jLabel10.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(0, 207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inicializaciones() throws ClassNotFoundException, FileNotFoundException {
        inventario = PersistenciaInventario.cargar();
        usuarios = PersistenciaUsuarios.cargar();
        prestamos = PersistenciaPrestamos.cargar();
        setTitle("ElectroLab Manager");
        setSize(900, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        
        areaTexto = new JTextArea();
        areaTexto.setEditable(false);
        JScrollPane scroll= new JScrollPane(areaTexto);
        add(scroll, BorderLayout.CENTER);
        
        JPanel panelBotones= new JPanel();
        panelBotones.setLayout(new GridLayout(4, 2));
        JButton btnRegistrar= new JButton("Registrar Usuario");
        JButton btnAgregar= new JButton("Agregar Componente");
        JButton btnPrestamo= new JButton("Realizar Prestamo");
        JButton btnMostrarInventario= new JButton("Mostrar Inventario");
        JButton btnMostrarPrestamos= new JButton("Mostrar Prestamos");
        JButton btnBuscar= new JButton("Buscar Componente");
        JButton btnDevolver= new JButton("Devolver Prestamo");
        JButton btnGuardar= new JButton("Guardar Datos");

        panelBotones.add(btnRegistrar);
        panelBotones.add(btnAgregar);
        panelBotones.add(btnPrestamo);
        panelBotones.add(btnMostrarInventario);
        panelBotones.add(btnMostrarPrestamos);
        panelBotones.add(btnBuscar);
        panelBotones.add(btnDevolver);
        panelBotones.add(btnGuardar);

        add(panelBotones, BorderLayout.WEST);

        
        btnRegistrar.addActionListener(e -> registrarUsuario());
        btnAgregar.addActionListener(e -> agregarComponente());
        btnPrestamo.addActionListener(e -> realizarPrestamo());
        btnMostrarInventario.addActionListener(e -> mostrarInventario());
        btnMostrarPrestamos.addActionListener(e -> mostrarPrestamos());
        btnBuscar.addActionListener(e -> buscarComponente());
        btnDevolver.addActionListener(e -> devolverPrestamo());
        btnGuardar.addActionListener(e -> guardarDatos());
    }

    private void registrarUsuario() {
        String[] opciones = {"Estudiante", "Docente"};
        String tipo = (String) JOptionPane.showInputDialog(this, "Seleccione tipo", "Usuario", JOptionPane.QUESTION_MESSAGE,
                null, opciones, opciones[0]);
        String nombre =JOptionPane.showInputDialog("Nombre:");
        String id =JOptionPane.showInputDialog("ID:");
        if (tipo.equals("Estudiante")) {
            String carrera = JOptionPane.showInputDialog("Carrera:");
            int semestre = Integer.parseInt(JOptionPane.showInputDialog("Semestre:"));
            Estudiante est = new Estudiante(nombre, id, carrera, semestre);
            usuarios.add(est);
            areaTexto.append("\nEstudiante registrado\n");
        } else {
            String especialidad = JOptionPane.showInputDialog("Especialidad:");
            Docente doc = new Docente(nombre, id, especialidad);
            usuarios.add(doc);
            areaTexto.append("\nDocente registrado\n");
        }
    }
    
    
    private void agregarComponente() {
        String[] opciones = {"Resistencia","Capacitor","Sensor"};
        String tipo = (String) JOptionPane.showInputDialog(this,"Tipo componente","Componente",JOptionPane.QUESTION_MESSAGE,
                        null,opciones,opciones[0]);
        String nombre= JOptionPane.showInputDialog("Nombre:");
        String codigo= JOptionPane.showInputDialog("Codigo:");
        int stock= Integer.parseInt(JOptionPane.showInputDialog("Stock:"));
        try {
            switch (tipo) {
                case "Resistencia":
                    double resistencia= Double.parseDouble(JOptionPane.showInputDialog("Resistencia:"));
                    inventario.agregarComponente(new Resistencia(nombre,codigo,stock,resistencia));
                    break;
                case "Capacitor":
                    double capacitancia= Double.parseDouble(JOptionPane.showInputDialog("Capacitancia:"));
                    inventario.agregarComponente(new Capacitor(nombre,codigo,stock,capacitancia));
                    break;
                case "Sensor":
                    String tipoMedicion= JOptionPane.showInputDialog("Tipo medicion:");
                    inventario.agregarComponente(new Sensor(nombre,codigo,stock,tipoMedicion));
                    break;
            }
            areaTexto.append("\nComponente agregado\n");
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    
    private void mostrarInventario() {
        areaTexto.setText("");
        for (ComponentesElectronicos c: inventario.getComponentes()) {
            areaTexto.append(c + "\n----------------\n");
        }
    }
    
    private void mostrarPrestamos() {
        areaTexto.setText("");
        for (Prestamo p : prestamos) {
            areaTexto.append(p + "\n----------------\n");
        }
    }

    private void buscarComponente() {
        String codigo= JOptionPane.showInputDialog("Codigo:");
        try {
            areaTexto.setText(inventario.buscarComponente(codigo).toString());
        } catch (ComponenteNoEncontradoException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

        
}
        
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ElectroLabFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
